dist: jammy

addons:
  apt:
    packages:
      - rabbitmq-server
      - openjdk-17-jdk
  sonarcloud:
    organization: techteamer

language: node_js

node_js:
  - 20
  - 22

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version version-number
  - export PATH="$HOME/.yarn/bin:$PATH"

git:
  depth: false

env:
  - NODE_ENV=travis

script:
  - yarn test
  - export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
  - export PATH=$JAVA_HOME/bin:$PATH
  - sonar-scanner
