dist: jammy

addons:
  apt:
    packages:
      - rabbitmq-server
      - openjdk-17-jdk
  sonarcloud:
    organization: techteamer

language: node_js

node_js:
  - 16
  - 18

git:
  depth: false

env:
  - NODE_ENV=travis

script:
  - yarn test
  - sonar-scanner
