dist: jammy

addons:
  apt:
    packages:
      - rabbitmq-server
  sonarcloud:
    organization: techteamer

language: node_js

node_js:
  - 16
  - 18

env:
  - NODE_ENV=travis

script:
  - yarn test
  - sonar-scanner
